spring:
    application:
        name: libraryapi
    datasource:
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.format_sql: true
    security: 
        oauth2:
            client:
                registration:
                    google:
                        client-id: 821140140382-3nhrnmenm7hmkhtbpqph7vsrh5cvlk5c.apps.googleusercontent.com
                        client-secret: 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

logging:
    file:
        name: app.log
    level:
        root: warn
        io:
            github:
                caioosm: trace
        org:
            springframework:
                web: debug
                security: trace


springdoc:
  override-with-generic-response: false