spring:
    application:
        name: libraryapi
#    profiles:
#        active: production
#SPRING_PROFILES_ACTIVE=production
    output:
        ansi:
            enabled: always
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
        username: ${DATASOURCE_USERNAME:postgres}
        password: ${DATASOURCE_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate.format_sql: true
    security: 
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
    file:
        name: app.log
    level:
        root: warn
        io:
            github:
                caioosm: trace
        org:
            springframework:
                web: debug
                security: warn

management:
    server:
        port: 9090
    endpoints:
      web:
        exposure:
            include: '*'


springdoc:
  override-with-generic-response: false


  # production
---
spring:
    config:
        activate:
            on-profile: production
    jpa:
        show-sql: false